    ###installing node.js 13 on server failed###
---
- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    # Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs
    # Use n version manager to use Node.js v13.8.0
    sudo npm install -g n
    sudo n 13.8.0
- name: "Install Nod.js 13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes